# Generated by Django 5.1.7 on 2025-04-01 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_source_added_by_source_company_source_tagged_company_and_more'),
        ('users', '0004_user_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('url__startswith', 'http')), name='check_valid_url'),
        ),
    ]
