# Generated by Django 5.1.7 on 2025-04-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_source_check_valid_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
