# Generated by Django 5.1.7 on 2025-04-01 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_source_check_valid_url'),
        ('story', '0002_story_added_by_story_company_story_source_and_more'),
        ('users', '0004_user_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='story',
            constraint=models.CheckConstraint(condition=models.Q(('article_url__startswith', 'http')), name='check_valid_article_url'),
        ),
    ]
