# Generated by Django 5.1.7 on 2025-04-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_story_check_valid_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='article_url',
            field=models.URLField(max_length=500),
        ),
    ]
